server:
  port: 8080
  # 测试用：设置最大线程数
  tomcat:
    max-threads: 1
spring:
  datasource:
    name: eda-third-party-interface
    url: jdbc:mysql://127.0.0.1:3306/block?useSSL=false&useUnicode=true&characterEncoding=utf8
    username: root
    password: 123456
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    filters: stat
    max-active: 200
    initial-size: 1
    max-wait: 60000
    min-idle: 1
    time-between-eviction-runs-millis: 60000
    min-evictableIdle-time-millis: 300000
    validation-query: select 'x'
    test-while-idle: true
    test-on-borrow: false
    test-on-return: false
    pool-prepared-statements: true
    max-open-prepared-statements: 20
  rabbitmq:
    host: 192.168.0.24
    password: 123456
    username: eda
    listener:
      type: simple
      simple:
        default-requeue-rejected: false
        acknowledge-mode: manual
mybatis-plus:
  mapper-locations: classpath:/mapper/*Mapper.xml
  #实体扫描，多个package用逗号或者分号分隔
  typeAliasesPackage: com.minstone.bd.eda.thirdparty.entity
  global-config:
    db-config:
      capital-mode: false
      db-type: mysql
      id-type: uuid
      logic-delete-value: 1
      logic-not-delete-value: 0
  configuration:
    map-underscore-to-camel-case: true
    cache-enabled: true
    call-setters-on-nulls: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
rocketmq:
  name-server: 192.168.0.128:9876
  producer:
    group: flow_group
    send-message-timeout: 3000